# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EvaluateSimilarity <- function(Mat, cluster) {
    .Call('Citrus_EvaluateSimilarity', PACKAGE = 'Citrus', Mat, cluster)
}

sampleFromMND <- function(n, p, M, U, V) {
    .Call('Citrus_sampleFromMND', PACKAGE = 'Citrus', n, p, M, U, V)
}

riwishart <- function(nu, V) {
    .Call('Citrus_riwishart', PACKAGE = 'Citrus', nu, V)
}

dmvnrmArma <- function(x, mean, sigma, logd = FALSE) {
    .Call('Citrus_dmvnrmArma', PACKAGE = 'Citrus', x, mean, sigma, logd)
}

dmvnrmRowArma <- function(x, mean, sigma, logd = FALSE) {
    .Call('Citrus_dmvnrmRowArma', PACKAGE = 'Citrus', x, mean, sigma, logd)
}

mvrnormArma <- function(mu, sigma) {
    .Call('Citrus_mvrnormArma', PACKAGE = 'Citrus', mu, sigma)
}

callpois <- function(x, alpha, log) {
    .Call('Citrus_callpois', PACKAGE = 'Citrus', x, alpha, log)
}

harmonic <- function(q) {
    .Call('Citrus_harmonic', PACKAGE = 'Citrus', q)
}

colmean <- function(x) {
    .Call('Citrus_colmean', PACKAGE = 'Citrus', x)
}

callKmeans <- function(x, k) {
    .Call('Citrus_callKmeans', PACKAGE = 'Citrus', x, k)
}

Cquantile <- function(x, q) {
    .Call('Citrus_Cquantile', PACKAGE = 'Citrus', x, q)
}

fastInverse <- function(psi, lambda, diag) {
    .Call('Citrus_fastInverse', PACKAGE = 'Citrus', psi, lambda, diag)
}

initialize_lambda <- function(Z_norm, X) {
    .Call('Citrus_initialize_lambda', PACKAGE = 'Citrus', Z_norm, X)
}

reorderMatF <- function(F) {
    .Call('Citrus_reorderMatF', PACKAGE = 'Citrus', F)
}

logratio <- function(active, q) {
    .Call('Citrus_logratio', PACKAGE = 'Citrus', active, q)
}

subsetMat <- function(X, neworder, byrow) {
    .Call('Citrus_subsetMat', PACKAGE = 'Citrus', X, neworder, byrow)
}

initilizationIBP <- function(X, k) {
    .Call('Citrus_initilizationIBP', PACKAGE = 'Citrus', X, k)
}

PLSinitilizationIBP <- function(Y, X, k1, k2) {
    .Call('Citrus_PLSinitilizationIBP', PACKAGE = 'Citrus', Y, X, k1, k2)
}

DirichletSpikeModel <- function(X, K, iniL, TruncateL, iter, nu0, sigma, r, s, alpha, mu0, Sigma0, kappa0, m, g, h, c, d, s1, s2, iter_to_average) {
    .Call('Citrus_DirichletSpikeModel', PACKAGE = 'Citrus', X, K, iniL, TruncateL, iter, nu0, sigma, r, s, alpha, mu0, Sigma0, kappa0, m, g, h, c, d, s1, s2, iter_to_average)
}

IBPfactormodel <- function(X, numk, iter, sigma, alpha, kappa, g, h, c, d, limit) {
    .Call('Citrus_IBPfactormodel', PACKAGE = 'Citrus', X, numk, iter, sigma, alpha, kappa, g, h, c, d, limit)
}

DirichletIBPModel <- function(X, K, iniL, TruncateL, iter, maxK, nu0, sigma, r, s, alpha, alpha2, mu0, Sigma0, kappa0, m, g, h, c, d, kappa, s1, s2, iter_to_average) {
    .Call('Citrus_DirichletIBPModel', PACKAGE = 'Citrus', X, K, iniL, TruncateL, iter, maxK, nu0, sigma, r, s, alpha, alpha2, mu0, Sigma0, kappa0, m, g, h, c, d, kappa, s1, s2, iter_to_average)
}

DirichletSpikePLSModel <- function(Y, X, k1, K, iniL, TruncateL, iter, nu0, sigma, r, s, alpha, mu0, Sigma0, kappa0, m, g, c, d, diagH, h1, h2, s1, s2, iter_to_average) {
    .Call('Citrus_DirichletSpikePLSModel', PACKAGE = 'Citrus', Y, X, k1, K, iniL, TruncateL, iter, nu0, sigma, r, s, alpha, mu0, Sigma0, kappa0, m, g, c, d, diagH, h1, h2, s1, s2, iter_to_average)
}

PLSIBPfactormodel <- function(Y, X, k1, k2, iter, sigma, alpha, kappa, diagH, g, h1, h2, c, d, limit) {
    .Call('Citrus_PLSIBPfactormodel', PACKAGE = 'Citrus', Y, X, k1, k2, iter, sigma, alpha, kappa, diagH, g, h1, h2, c, d, limit)
}

DirichletIBPPLSModel <- function(Y, X, k1, K, iniL, TruncateL, iter, maxK, nu0, sigma, r, s, alpha, alpha2, mu0, Sigma0, kappa0, m, g, c, d, kappa, diagH, h1, h2, s1, s2, iter_to_average) {
    .Call('Citrus_DirichletIBPPLSModel', PACKAGE = 'Citrus', Y, X, k1, K, iniL, TruncateL, iter, maxK, nu0, sigma, r, s, alpha, alpha2, mu0, Sigma0, kappa0, m, g, c, d, kappa, diagH, h1, h2, s1, s2, iter_to_average)
}

factorEM <- function(X, Y, k, iter) {
    .Call('Citrus_factorEM', PACKAGE = 'Citrus', X, Y, k, iter)
}

PLSfactorEM <- function(X, Y, k1, k2, iter) {
    .Call('Citrus_PLSfactorEM', PACKAGE = 'Citrus', X, Y, k1, k2, iter)
}

NaivePCA <- function(X, Y, k1, k2) {
    .Call('Citrus_NaivePCA', PACKAGE = 'Citrus', X, Y, k1, k2)
}

PLSinitilization <- function(Y, X, k1, k2) {
    .Call('Citrus_PLSinitilization', PACKAGE = 'Citrus', Y, X, k1, k2)
}

callLasso <- function(Y, X, D, lam) {
    .Call('Citrus_callLasso', PACKAGE = 'Citrus', Y, X, D, lam)
}

PLSfactorEMpenalty <- function(Y, X, k1, k2, iter, lambda_y, lambda_x, lambda_u, lam, tol) {
    .Call('Citrus_PLSfactorEMpenalty', PACKAGE = 'Citrus', Y, X, k1, k2, iter, lambda_y, lambda_x, lambda_u, lam, tol)
}

floss <- function(X, Y) {
    .Call('Citrus_floss', PACKAGE = 'Citrus', X, Y)
}

InNotIn <- function(x, n) {
    .Call('Citrus_InNotIn', PACKAGE = 'Citrus', x, n)
}

PLSfactorEMpenaltyTrain <- function(Y, X, k1, k2, iter, penalty, tol) {
    .Call('Citrus_PLSfactorEMpenaltyTrain', PACKAGE = 'Citrus', Y, X, k1, k2, iter, penalty, tol)
}

CountSparsity <- function(X) {
    .Call('Citrus_CountSparsity', PACKAGE = 'Citrus', X)
}

PLSfactorEMpenaltyCVonefold <- function(trainingY, trainingX, tuneY, tuneX, k1, k2, iter, penalty, tol) {
    .Call('Citrus_PLSfactorEMpenaltyCVonefold', PACKAGE = 'Citrus', trainingY, trainingX, tuneY, tuneX, k1, k2, iter, penalty, tol)
}

PLSfactorEMpenaltyNfoldCV <- function(Y, X, k1, k2, iter, kfold, penalty, tol) {
    .Call('Citrus_PLSfactorEMpenaltyNfoldCV', PACKAGE = 'Citrus', Y, X, k1, k2, iter, kfold, penalty, tol)
}

PLSfactorEMpenaltyGivenPen <- function(Y, X, k1, k2, iter, pen, tol) {
    .Call('Citrus_PLSfactorEMpenaltyGivenPen', PACKAGE = 'Citrus', Y, X, k1, k2, iter, pen, tol)
}

EM_for_one_chunk <- function(W, lambda, psi, k1, k2, p, E_Z_w, Var_Z_w) {
    .Call('Citrus_EM_for_one_chunk', PACKAGE = 'Citrus', W, lambda, psi, k1, k2, p, E_Z_w, Var_Z_w)
}

PLSfactorEMchunk <- function(X, Y, k1, k2, iter, chunk) {
    .Call('Citrus_PLSfactorEMchunk', PACKAGE = 'Citrus', X, Y, k1, k2, iter, chunk)
}

